import type { ContractRecord } from "@/lib/contracts/filter-contracts";

export const DEMO_CONTRACTS: readonly ContractRecord[] = [
  {
    id: "HD-2026-0184",
    title: "Triển khai nền tảng dữ liệu vận hành",
    client: "Công ty Cổ phần Minh Hải",
    department: "Giải pháp số",
    owner: "Nguyễn Minh Anh",
    type: "SERVICE",
    status: "ACTIVE",
    value: 1_280_000_000,
    signedAt: "2026-07-08",
    expiresAt: "2027-01-08",
  },
  {
    id: "HD-2026-0179",
    title: "Bảo trì hạ tầng mạng lõi",
    client: "Bệnh viện An Phúc",
    department: "Hạ tầng",
    owner: "Trần Quốc Huy",
    type: "MAINTENANCE",
    status: "PENDING",
    value: 460_000_000,
    signedAt: "2026-06-16",
    expiresAt: "2026-12-16",
  },
  {
    id: "HD-2026-0168",
    title: "Cung cấp thiết bị giám sát an toàn",
    client: "Tổng công ty Đông Thành",
    department: "Kinh doanh",
    owner: "Đỗ Ngọc Mai",
    type: "SUPPLY",
    status: "EXPIRING",
    value: 2_360_000_000,
    signedAt: "2026-04-22",
    expiresAt: "2026-09-05",
  },
  {
    id: "HD-2026-0153",
    title: "Thỏa thuận bảo mật dữ liệu dự án",
    client: "Ngân hàng Hưng Việt",
    department: "Pháp chế",
    owner: "Vũ Thanh Tùng",
    type: "NDA",
    status: "ACTIVE",
    value: 0,
    signedAt: "2026-03-11",
    expiresAt: "2028-03-11",
  },
  {
    id: "HD-2026-0137",
    title: "Tư vấn kiến trúc trung tâm điều hành",
    client: "Trung tâm Điều hành Số",
    department: "Giải pháp số",
    owner: "Nguyễn Minh Anh",
    type: "SERVICE",
    status: "EXPIRED",
    value: 780_000_000,
    signedAt: "2026-01-17",
    expiresAt: "2026-07-17",
  },
  {
    id: "HD-2026-0191",
    title: "Dịch vụ đánh giá an toàn thông tin",
    client: "Công ty Dược phẩm Nam Việt",
    department: "An toàn thông tin",
    owner: "Lê Gia Bảo",
    type: "SERVICE",
    status: "DRAFT",
    value: 615_000_000,
    signedAt: "2026-08-02",
    expiresAt: "2027-02-02",
  },
  {
    id: "HD-2025-0116",
    title: "Bảo trì hệ thống lưu trữ tập trung",
    client: "Cảng Quốc tế Nam Sơn",
    department: "Hạ tầng",
    owner: "Trần Quốc Huy",
    type: "MAINTENANCE",
    status: "EXPIRING",
    value: 920_000_000,
    signedAt: "2025-09-28",
    expiresAt: "2026-08-28",
  },
];

export const CONTRACT_DEPARTMENTS = [
  "Giải pháp số",
  "Hạ tầng",
  "Kinh doanh",
  "Pháp chế",
  "An toàn thông tin",
] as const;
